### ISSUE TITLE
Few changes

### ISSUE THREAD

**Issue by mathias22osterhagen22** [HrithikMittal/loopback4-authorization#5]
Hello dear friend,

Thank you again for your amazing work that makes my life so easier!

There is two last stuff that you could do to improve this repo: 

1.   Add the ` security: OPERATION_SECURITY_SPEC` prop to the routes to show the little "lock" icon on the /explore UI
![image](https://user-images.githubusercontent.com/60438474/94565468-8cae8000-0269-11eb-927f-fcc215a95487.png)
![image](https://user-images.githubusercontent.com/60438474/94565593-b2d42000-0269-11eb-8035-7477eaf8041a.png)

### => Without it the /explore will not add the authorization header and a 401 will always be returned during a "Try it out" <= 

2.   Add a little sentence at the end of the README.md to remember to migrate again the database at the end of the modifications (to add the permission column) with `npm run clean; npm run build; npm run migrate` (I forgot 😄 )

Thank you!

**Comment by HrithikMittal** [comment]
Thank you so much for your feedback. But If you don't mind can you please do these changes and create the PR. I will merge it.

**Comment by mathias22osterhagen22** [comment]
Hello @HrithikMittal , I made them :)
